/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiReleasesLatestRouteImport } from './routes/api/releases/latest'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReleasesLatestRoute = ApiReleasesLatestRouteImport.update({
  id: '/api/releases/latest',
  path: '/api/releases/latest',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/releases/latest': typeof ApiReleasesLatestRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/releases/latest': typeof ApiReleasesLatestRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/releases/latest': typeof ApiReleasesLatestRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/releases/latest'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/releases/latest'
  id: '__root__' | '/' | '/api/releases/latest'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiReleasesLatestRoute: typeof ApiReleasesLatestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/releases/latest': {
      id: '/api/releases/latest'
      path: '/api/releases/latest'
      fullPath: '/api/releases/latest'
      preLoaderRoute: typeof ApiReleasesLatestRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiReleasesLatestRoute: ApiReleasesLatestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
