/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as EnterpriseRouteImport } from './routes/enterprise'
import { Route as DownloadRouteImport } from './routes/download'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ChangelogRouteImport } from './routes/changelog'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocsUpdatesRouteImport } from './routes/docs.updates'
import { Route as DocsTroubleshootingRouteImport } from './routes/docs.troubleshooting'
import { Route as DocsToolsRouteImport } from './routes/docs.tools'
import { Route as DocsTerminalRouteImport } from './routes/docs.terminal'
import { Route as DocsProjectsRouteImport } from './routes/docs.projects'
import { Route as DocsPermissionsRouteImport } from './routes/docs.permissions'
import { Route as DocsInstallationRouteImport } from './routes/docs.installation'
import { Route as DocsGitRouteImport } from './routes/docs.git'
import { Route as DocsGettingStartedRouteImport } from './routes/docs.getting-started'
import { Route as DocsFileAccessRouteImport } from './routes/docs.file-access'
import { Route as DocsFaqRouteImport } from './routes/docs.faq'
import { Route as DocsConfigurationRouteImport } from './routes/docs.configuration'
import { Route as DocsChatsRouteImport } from './routes/docs.chats'
import { Route as ApiReleasesLatestRouteImport } from './routes/api/releases/latest'

const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const EnterpriseRoute = EnterpriseRouteImport.update({
  id: '/enterprise',
  path: '/enterprise',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadRoute = DownloadRouteImport.update({
  id: '/download',
  path: '/download',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangelogRoute = ChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsUpdatesRoute = DocsUpdatesRouteImport.update({
  id: '/updates',
  path: '/updates',
  getParentRoute: () => DocsRoute,
} as any)
const DocsTroubleshootingRoute = DocsTroubleshootingRouteImport.update({
  id: '/troubleshooting',
  path: '/troubleshooting',
  getParentRoute: () => DocsRoute,
} as any)
const DocsToolsRoute = DocsToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => DocsRoute,
} as any)
const DocsTerminalRoute = DocsTerminalRouteImport.update({
  id: '/terminal',
  path: '/terminal',
  getParentRoute: () => DocsRoute,
} as any)
const DocsProjectsRoute = DocsProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => DocsRoute,
} as any)
const DocsPermissionsRoute = DocsPermissionsRouteImport.update({
  id: '/permissions',
  path: '/permissions',
  getParentRoute: () => DocsRoute,
} as any)
const DocsInstallationRoute = DocsInstallationRouteImport.update({
  id: '/installation',
  path: '/installation',
  getParentRoute: () => DocsRoute,
} as any)
const DocsGitRoute = DocsGitRouteImport.update({
  id: '/git',
  path: '/git',
  getParentRoute: () => DocsRoute,
} as any)
const DocsGettingStartedRoute = DocsGettingStartedRouteImport.update({
  id: '/getting-started',
  path: '/getting-started',
  getParentRoute: () => DocsRoute,
} as any)
const DocsFileAccessRoute = DocsFileAccessRouteImport.update({
  id: '/file-access',
  path: '/file-access',
  getParentRoute: () => DocsRoute,
} as any)
const DocsFaqRoute = DocsFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => DocsRoute,
} as any)
const DocsConfigurationRoute = DocsConfigurationRouteImport.update({
  id: '/configuration',
  path: '/configuration',
  getParentRoute: () => DocsRoute,
} as any)
const DocsChatsRoute = DocsChatsRouteImport.update({
  id: '/chats',
  path: '/chats',
  getParentRoute: () => DocsRoute,
} as any)
const ApiReleasesLatestRoute = ApiReleasesLatestRouteImport.update({
  id: '/api/releases/latest',
  path: '/api/releases/latest',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/changelog': typeof ChangelogRoute
  '/contact': typeof ContactRoute
  '/docs': typeof DocsRouteWithChildren
  '/download': typeof DownloadRoute
  '/enterprise': typeof EnterpriseRoute
  '/features': typeof FeaturesRoute
  '/how-it-works': typeof HowItWorksRoute
  '/security': typeof SecurityRoute
  '/docs/chats': typeof DocsChatsRoute
  '/docs/configuration': typeof DocsConfigurationRoute
  '/docs/faq': typeof DocsFaqRoute
  '/docs/file-access': typeof DocsFileAccessRoute
  '/docs/getting-started': typeof DocsGettingStartedRoute
  '/docs/git': typeof DocsGitRoute
  '/docs/installation': typeof DocsInstallationRoute
  '/docs/permissions': typeof DocsPermissionsRoute
  '/docs/projects': typeof DocsProjectsRoute
  '/docs/terminal': typeof DocsTerminalRoute
  '/docs/tools': typeof DocsToolsRoute
  '/docs/troubleshooting': typeof DocsTroubleshootingRoute
  '/docs/updates': typeof DocsUpdatesRoute
  '/api/releases/latest': typeof ApiReleasesLatestRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/changelog': typeof ChangelogRoute
  '/contact': typeof ContactRoute
  '/docs': typeof DocsRouteWithChildren
  '/download': typeof DownloadRoute
  '/enterprise': typeof EnterpriseRoute
  '/features': typeof FeaturesRoute
  '/how-it-works': typeof HowItWorksRoute
  '/security': typeof SecurityRoute
  '/docs/chats': typeof DocsChatsRoute
  '/docs/configuration': typeof DocsConfigurationRoute
  '/docs/faq': typeof DocsFaqRoute
  '/docs/file-access': typeof DocsFileAccessRoute
  '/docs/getting-started': typeof DocsGettingStartedRoute
  '/docs/git': typeof DocsGitRoute
  '/docs/installation': typeof DocsInstallationRoute
  '/docs/permissions': typeof DocsPermissionsRoute
  '/docs/projects': typeof DocsProjectsRoute
  '/docs/terminal': typeof DocsTerminalRoute
  '/docs/tools': typeof DocsToolsRoute
  '/docs/troubleshooting': typeof DocsTroubleshootingRoute
  '/docs/updates': typeof DocsUpdatesRoute
  '/api/releases/latest': typeof ApiReleasesLatestRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/changelog': typeof ChangelogRoute
  '/contact': typeof ContactRoute
  '/docs': typeof DocsRouteWithChildren
  '/download': typeof DownloadRoute
  '/enterprise': typeof EnterpriseRoute
  '/features': typeof FeaturesRoute
  '/how-it-works': typeof HowItWorksRoute
  '/security': typeof SecurityRoute
  '/docs/chats': typeof DocsChatsRoute
  '/docs/configuration': typeof DocsConfigurationRoute
  '/docs/faq': typeof DocsFaqRoute
  '/docs/file-access': typeof DocsFileAccessRoute
  '/docs/getting-started': typeof DocsGettingStartedRoute
  '/docs/git': typeof DocsGitRoute
  '/docs/installation': typeof DocsInstallationRoute
  '/docs/permissions': typeof DocsPermissionsRoute
  '/docs/projects': typeof DocsProjectsRoute
  '/docs/terminal': typeof DocsTerminalRoute
  '/docs/tools': typeof DocsToolsRoute
  '/docs/troubleshooting': typeof DocsTroubleshootingRoute
  '/docs/updates': typeof DocsUpdatesRoute
  '/api/releases/latest': typeof ApiReleasesLatestRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/changelog'
    | '/contact'
    | '/docs'
    | '/download'
    | '/enterprise'
    | '/features'
    | '/how-it-works'
    | '/security'
    | '/docs/chats'
    | '/docs/configuration'
    | '/docs/faq'
    | '/docs/file-access'
    | '/docs/getting-started'
    | '/docs/git'
    | '/docs/installation'
    | '/docs/permissions'
    | '/docs/projects'
    | '/docs/terminal'
    | '/docs/tools'
    | '/docs/troubleshooting'
    | '/docs/updates'
    | '/api/releases/latest'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/changelog'
    | '/contact'
    | '/docs'
    | '/download'
    | '/enterprise'
    | '/features'
    | '/how-it-works'
    | '/security'
    | '/docs/chats'
    | '/docs/configuration'
    | '/docs/faq'
    | '/docs/file-access'
    | '/docs/getting-started'
    | '/docs/git'
    | '/docs/installation'
    | '/docs/permissions'
    | '/docs/projects'
    | '/docs/terminal'
    | '/docs/tools'
    | '/docs/troubleshooting'
    | '/docs/updates'
    | '/api/releases/latest'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/changelog'
    | '/contact'
    | '/docs'
    | '/download'
    | '/enterprise'
    | '/features'
    | '/how-it-works'
    | '/security'
    | '/docs/chats'
    | '/docs/configuration'
    | '/docs/faq'
    | '/docs/file-access'
    | '/docs/getting-started'
    | '/docs/git'
    | '/docs/installation'
    | '/docs/permissions'
    | '/docs/projects'
    | '/docs/terminal'
    | '/docs/tools'
    | '/docs/troubleshooting'
    | '/docs/updates'
    | '/api/releases/latest'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ChangelogRoute: typeof ChangelogRoute
  ContactRoute: typeof ContactRoute
  DocsRoute: typeof DocsRouteWithChildren
  DownloadRoute: typeof DownloadRoute
  EnterpriseRoute: typeof EnterpriseRoute
  FeaturesRoute: typeof FeaturesRoute
  HowItWorksRoute: typeof HowItWorksRoute
  SecurityRoute: typeof SecurityRoute
  ApiReleasesLatestRoute: typeof ApiReleasesLatestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enterprise': {
      id: '/enterprise'
      path: '/enterprise'
      fullPath: '/enterprise'
      preLoaderRoute: typeof EnterpriseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/download': {
      id: '/download'
      path: '/download'
      fullPath: '/download'
      preLoaderRoute: typeof DownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changelog': {
      id: '/changelog'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof ChangelogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/updates': {
      id: '/docs/updates'
      path: '/updates'
      fullPath: '/docs/updates'
      preLoaderRoute: typeof DocsUpdatesRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/troubleshooting': {
      id: '/docs/troubleshooting'
      path: '/troubleshooting'
      fullPath: '/docs/troubleshooting'
      preLoaderRoute: typeof DocsTroubleshootingRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/tools': {
      id: '/docs/tools'
      path: '/tools'
      fullPath: '/docs/tools'
      preLoaderRoute: typeof DocsToolsRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/terminal': {
      id: '/docs/terminal'
      path: '/terminal'
      fullPath: '/docs/terminal'
      preLoaderRoute: typeof DocsTerminalRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/projects': {
      id: '/docs/projects'
      path: '/projects'
      fullPath: '/docs/projects'
      preLoaderRoute: typeof DocsProjectsRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/permissions': {
      id: '/docs/permissions'
      path: '/permissions'
      fullPath: '/docs/permissions'
      preLoaderRoute: typeof DocsPermissionsRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/installation': {
      id: '/docs/installation'
      path: '/installation'
      fullPath: '/docs/installation'
      preLoaderRoute: typeof DocsInstallationRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/git': {
      id: '/docs/git'
      path: '/git'
      fullPath: '/docs/git'
      preLoaderRoute: typeof DocsGitRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/getting-started': {
      id: '/docs/getting-started'
      path: '/getting-started'
      fullPath: '/docs/getting-started'
      preLoaderRoute: typeof DocsGettingStartedRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/file-access': {
      id: '/docs/file-access'
      path: '/file-access'
      fullPath: '/docs/file-access'
      preLoaderRoute: typeof DocsFileAccessRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/faq': {
      id: '/docs/faq'
      path: '/faq'
      fullPath: '/docs/faq'
      preLoaderRoute: typeof DocsFaqRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/configuration': {
      id: '/docs/configuration'
      path: '/configuration'
      fullPath: '/docs/configuration'
      preLoaderRoute: typeof DocsConfigurationRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/chats': {
      id: '/docs/chats'
      path: '/chats'
      fullPath: '/docs/chats'
      preLoaderRoute: typeof DocsChatsRouteImport
      parentRoute: typeof DocsRoute
    }
    '/api/releases/latest': {
      id: '/api/releases/latest'
      path: '/api/releases/latest'
      fullPath: '/api/releases/latest'
      preLoaderRoute: typeof ApiReleasesLatestRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DocsRouteChildren {
  DocsChatsRoute: typeof DocsChatsRoute
  DocsConfigurationRoute: typeof DocsConfigurationRoute
  DocsFaqRoute: typeof DocsFaqRoute
  DocsFileAccessRoute: typeof DocsFileAccessRoute
  DocsGettingStartedRoute: typeof DocsGettingStartedRoute
  DocsGitRoute: typeof DocsGitRoute
  DocsInstallationRoute: typeof DocsInstallationRoute
  DocsPermissionsRoute: typeof DocsPermissionsRoute
  DocsProjectsRoute: typeof DocsProjectsRoute
  DocsTerminalRoute: typeof DocsTerminalRoute
  DocsToolsRoute: typeof DocsToolsRoute
  DocsTroubleshootingRoute: typeof DocsTroubleshootingRoute
  DocsUpdatesRoute: typeof DocsUpdatesRoute
}

const DocsRouteChildren: DocsRouteChildren = {
  DocsChatsRoute: DocsChatsRoute,
  DocsConfigurationRoute: DocsConfigurationRoute,
  DocsFaqRoute: DocsFaqRoute,
  DocsFileAccessRoute: DocsFileAccessRoute,
  DocsGettingStartedRoute: DocsGettingStartedRoute,
  DocsGitRoute: DocsGitRoute,
  DocsInstallationRoute: DocsInstallationRoute,
  DocsPermissionsRoute: DocsPermissionsRoute,
  DocsProjectsRoute: DocsProjectsRoute,
  DocsTerminalRoute: DocsTerminalRoute,
  DocsToolsRoute: DocsToolsRoute,
  DocsTroubleshootingRoute: DocsTroubleshootingRoute,
  DocsUpdatesRoute: DocsUpdatesRoute,
}

const DocsRouteWithChildren = DocsRoute._addFileChildren(DocsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ChangelogRoute: ChangelogRoute,
  ContactRoute: ContactRoute,
  DocsRoute: DocsRouteWithChildren,
  DownloadRoute: DownloadRoute,
  EnterpriseRoute: EnterpriseRoute,
  FeaturesRoute: FeaturesRoute,
  HowItWorksRoute: HowItWorksRoute,
  SecurityRoute: SecurityRoute,
  ApiReleasesLatestRoute: ApiReleasesLatestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
